### ISSUE TITLE
Failing to save Thread commissioning config in NVM

### ISSUE THREAD

**Issue by bentcooke** [ARMmbed/mbed-os-example-mesh-minimal#190]
AFter successful commissioning, NVM does not appear to be storing the config correctly when using MESH_SD_CARD for the storage method.  When the device is reset the following message appears:

[ERR ][TjoA]: Failed to read link configuration settings from NVM

How does the SD need to be prepared for the config to be stored/read correctly?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3698

**Comment by artokin** [comment]
The failure occurs Nanostack initialisation order has changed a bit. The application tries to set file system root-path to Nanostack but because Nanostack is not yet initialised the root-path set fails. Therefore file system operation will fail. To fix this we need to modify Nanostack initialisation order.

**Comment by bentcooke** [comment]
@artokin Thanks for the info on the failure mode.  I applied the fixes you mentioned and can confirm the commissioning config is being saved / restored correctly now.

**Comment by ashok-rao** [comment]
Looks like issue is resolved. @bentcooke please re-open if not. Thanks all, closing this issue now.

**Comment by ashok-rao** [comment]
Thanks @artokin, your fix PR has already been marked for release in 5.9.1. I think it's safe to close this for 5.9.0 OoB now.
