### ISSUE TITLE
Can't export the project with online compiler

### ISSUE THREAD

**Issue by balamk07** [ARMmbed/mbed-os-example-mesh-minimal#26]
Hi,

I couldn't export this project to any of the external toolchains supported by mbed online compiler. Export option works with mbed-cli, but the project file generated by it doesn't compile for KDS or IAR toolchain. mbed cli pulls in all the source files under mbed-os as well as the protocol stack directories causing many compilation errors. Could you please fix the export option for this project so that it can be exported to different toolchain from mbed online compiler?

Thanks,
Bala

**Comment by SeppoTakalo** [comment]
This example seems to export with the offline tool.

@theotherjimmy Can you help, what is the problem here?

I tried to import this app to online tool. Works fine, builds fine.

Then I tried to export:
![screen shot 2016-10-25 at 16 23 52](https://cloud.githubusercontent.com/assets/3104794/19688651/41d3c54c-9ad3-11e6-89f1-5f4a7b71ce78.png)

**Comment by hasnainvirk** [comment]
@balamk07 Is it still valid ?

**Comment by balamk07** [comment]
@hasnainvirk I just tried to export the project with mbed online compiler. Unfortunately the issue still exists

**Comment by hasnainvirk** [comment]
@screamerbg Can you please help here ?

**Comment by SeppoTakalo** [comment]
Closing this as this is a online compiler issue, not related to this app.
