### ISSUE TITLE
make_gcc_arm and make_iar throwing errors when running make

### ISSUE THREAD

**Issue by brandonboesch** [ARMmbed/mbed-os-example-mesh-minimal#95]
After exporting with make_gcc_arm, and then running make, the following error occurs:

![capture](https://user-images.githubusercontent.com/16062082/27048875-17c75fb6-4f73-11e7-9887-83ba8ee20da0.PNG)

After exporting with make_iar, and then running make, the following error occurs:
![image](https://user-images.githubusercontent.com/16062082/27051427-aad95996-4f7b-11e7-952c-6adf5a5e0762.png)

**Comment by SeppoTakalo** [comment]
Thanks for reporting.
I assume that you have KW24D platform which suffers from small RAM size.
Static allocations cannot be more that 31kB because this device have its RAM split into two equal sized sections. GCC linker can only utilize one block for one section .BSS, .DATA or stack.

Couple of ways to workaround this:
* Use ARM compiler. This will allow .BSS and .DATA to grow from `m_data` to `m_data2` section.
* Wait for RC2. [This](https://github.com/ARMmbed/mbed-os/pull/4493) will drop 14kB of RAM usage
* Follow instructions for [memory optimisations of this application](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/blob/master/README.md#memory-optimizations).

**Comment by AriParkkila** [comment]
@brandonboesch The "make error 2" is probably due to missing path to compiler? I had the same error although I have correct paths in mbed config (GCC_ARM_PATH, IAR_PATH). It was not even enough to update PATH in local DOS prompt. I finally managed to fix it by setting Windows 10 System wide PATH and/or by hacking full path in the exported Makefile.

So I guess that "make error 2" should probably go to mbed CLI? Maybe you want to open a ticket for them :)

**Comment by SeppoTakalo** [comment]
OK.
Then I will close this.
CLI related issues should be related to mbed-cli repo.

**Comment by brandonboesch** [comment]
It has the path variable added for gcc-6, and is compiling all the c files, but the error happens at the end of the compile during the link process.

**Comment by brandonboesch** [comment]
In regards to make_iar, I updated the path variable in windows as recommended, and tried the memory optimization recommended in the readme by adding the following to the mbed_app.json file:
"macros": ["MBEDTLS_USER_CONFIG_FILE=\"mbedtls_config.h\""]

It is now throwing the following errors:
![image](https://user-images.githubusercontent.com/16062082/27149666-f04ac660-5109-11e7-978f-6b033b453aa2.png)

**Comment by theotherjimmy** [comment]
@brandonboesch Did you export after doing the memory optimization from the readme? Order matters!

**Comment by brandonboesch** [comment]
@theotherjimmy, Yes, I added the memory optimization to mbed_app.json and then exported, in that order.

**Comment by theotherjimmy** [comment]
@brandonboesch @SeppoTakalo Considering that this example has trouble fitting, could we resolve this by suggesting that users export with the "develop" or "release" profiles?

**Comment by MarceloSalazar** [comment]
@brandonboesch @SeppoTakalo could you share your thoughts on @theotherjimmy question?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3192

**Comment by SeppoTakalo** [comment]
I have no knowledge how to export with "release" profile.
Can someone specify which parameter it is, help does not show it:
```
$ mbed export --help
usage: mbed export [-h] [-i IDE] [-m TARGET] [--source SOURCE] [-c] [-S] [-v]
                   [-vv]

Generate IDE project files for the current program.

optional arguments:
  -h, --help            show this help message and exit
  -i IDE, --ide IDE     IDE to create project files for. Example: UVISION4,
                        UVISION5, GCC_ARM, IAR, COIDE
  -m TARGET, --target TARGET
                        Export for target MCU. Example: K64F, NUCLEO_F401RE,
                        NRF51822...
  --source SOURCE       Source directory. Default: . (current dir)
  -c, --clean           Clean the build directory before compiling
  -S, --supported       Shows supported matrix of targets and toolchains
  -v, --verbose         Verbose diagnostic output
  -vv, --very_verbose   Very verbose diagnostic output
```

Otherwise, this whole issue is now memory-fitting problem for some platform.

**Comment by MarceloSalazar** [comment]
https://docs.mbed.com/docs/mbed-os-handbook/en/latest/dev_tools/build_profiles/

**Comment by SeppoTakalo** [comment]
I cannot test this. exporters seems to be failing https://github.com/ARMmbed/mbed-os/issues/5131

**Comment by SeppoTakalo** [comment]
This issue will be fixed by appending the documentation.
